### ISSUE TITLE
Make developer's life easier 

### ISSUE THREAD

**Issue by pBouillon** [pBouillon/Sublime_text_snippets#1]
Development can be fastidious but, we have plenty of tools to help us.
Bring your most useful snippets of any language to help sublime text users !

**Comment by weirdGuy** [comment]
#2 submitted

**Comment by pBouillon** [comment]
@weirdGuy merged !

**Comment by pBouillon** [comment]
@weirdGuy Could you add this to the README.md please?

**Comment by weirdGuy** [comment]
@pBouillon already did

**Comment by pBouillon** [comment]
@weirdGuy My mistake, you did, thanks for helping !
